### ISSUE TITLE
Use correct config

### ISSUE THREAD

**Issue by bolah2009** [FSolM/react-bookstore#4]
Please let's use the [**correct config files**](https://github.com/microverseinc/linters-config/tree/master/react-redux).

- The config file should be `.eslintrc.json` with the right content, see https://github.com/FSolM/react-bookstore/pull/2#discussion_r361514676

- The `stickler.yml` file should have the right contents too, see https://github.com/FSolM/react-bookstore/pull/2#discussion_r361514488

![image](https://user-images.githubusercontent.com/36057474/71924065-8b46a000-318e-11ea-8f37-02c188bde393.png)

See https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/

If there's a reason why the config file needs to be changed, use the inline comments instead, see https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments.

If the config is absolutely necessary, open a PR in the linter config repo.

https://github.com/FSolM/react-bookstore/blob/388951d76ceb1202b2a681e0c8807ab34a0fcf20/.stickler.yml#L1-L9

**Comment by FSolM** [comment]
yeah, as I mentioned in that comment, I've been using both config files since the JS section and they work as a charm, won't change them since there were no problems with them in the first place
